/*
DATA PROFILING :

STEP 1 : STRUCTURE 
*/

--ROW COUNT :

SELECT 
	'staging.customers' AS Table_name,
	COUNT(*) AS Row_Count
FROM staging.customers  

UNION ALL

SELECT
	'staging.products',
	COUNT(*) 
FROM staging.products

UNION ALL

SELECT 
	'staging.orders',
	COUNT(*)
FROM staging.orders  

UNION ALL

SELECT 
	'staging.order_details',
	COUNT(*) 
FROM staging.order_details

UNION ALL

SELECT 
	'staging.reviews',
	COUNT(*)  
FROM staging.reviews

UNION ALL

SELECT 
	'staging.returns',
	COUNT(*)  
FROM staging.returns

UNION ALL 

SELECT
	'staging.promotions',
	COUNT(*) 
FROM staging.promotions



--COLUMN COUNT 

--CUSTOMERS
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'customers'
ORDER BY ORDINAL_POSITION;

--products
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'products'
ORDER BY ORDINAL_POSITION;

--orders
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'orders'
ORDER BY ORDINAL_POSITION;


--order_details

SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'order_details'
ORDER BY ORDINAL_POSITION;

--reviews
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'reviews'
ORDER BY ORDINAL_POSITION;

--returns
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'returns'
ORDER BY ORDINAL_POSITION;

--promotions
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'staging' AND TABLE_NAME = 'promotions'
ORDER BY ORDINAL_POSITION;